context: talos-k8s-proxmox
contexts:
    talos-k8s-proxmox:
        endpoints:
            - api.cluster.local
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBbmFHTzZQQlJFbjIwajgyS0ZleU1JVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdNVEEyTURFME56VTVXaGNOTXpZd01UQTBNREUwTnpVNVdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUFuVWdUMkRXbmZRMEZzdUJrVWFCa01NeUU3eDNFVy9HZU51CmlOWWdmZDBIbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkppeHdWSTJKazkreGlQeQpqMmVRQmYyZ2tQMCtNQVVHQXl0bGNBTkJBTklkN2dGMTNpNjVxYmkzSXlmalplM2hYVkpzcm44S0pVV25tZTUwCjR1UEhhNEptM0xJdFlMNWU5bng5eGtHNFNuYUg1V3VjUndRTjVNU1d0ZW8zZlEwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLRENCMjZBREFnRUNBaEFCcDVsM3FFa0VkdW94QlVGZ2pTaE1NQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQXhNRFl3TVRRM05UbGFGdzB5TnpBeE1EWXdNVFEzTlRsYU1CTXhFVEFQQmdOVgpCQW9UQ0c5ek9tRmtiV2x1TUNvd0JRWURLMlZ3QXlFQWRSODBDclZObmExdnFvc1lQNVBaL212QmVtVUxsQWU1CjgwTDNUYzVUWDRhalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0QKQWpBZkJnTlZIU01FR0RBV2dCU1lzY0ZTTmlaUGZzWWo4bzlua0FYOW9KRDlQakFGQmdNclpYQURRUUQrQnk3ZApTUFBaV29tdTNycDFydlZzUllrWm5oL1Z1SnZQbCt6SmVGdFM3TmxHUGlFU2x2UkEyUmc1cGdkUEo0c0VITEtGCnhzekdlWS9KeDh2V3ZhNE8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        key: ENC[AES256_GCM,data:wXlIejj8IirYWSdz7V1obKDI1zFMv9+t+zAUFFEflM1FRAFjdUXTGqkkTdgsNbmdMcusF+cPNgeHeYKBCeW/5m5uUb0LfHAx9zlcmcr3QYGPkV3O7K77S6ABIdJHBB14DaH5+moKKiTAdNBH22ihDFnTPjQk87ZwAp3d2QwxuD4b180dUizhEvpdYmI9OL0htDO0QPOV7inT2pSnmQztma6vRgPKrwztAh8h+00RV8JZ3hZo,iv:ZkAoXwjpqruAXthdYkyahG0mAM6Wi++GPY1NInT6Do0=,tag:d1R10lR2tPCNtxWOTeXxZg==,type:str]
sops:
    age:
        - recipient: age1ngvggfld4elq68926uczkes9rcqfjhnqn0tr6l8avyp4h46qzucqvx3sdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKS2ZlNzROajlPQmFOZGI1
            VUIraEVRM015ZkZRMldyMWwySHM5enhzZUJNCkhWaWl3ZnI0VTlndmUrSDYvZis1
            VXgyODJ5b05nRTc3VlBGcjJCaGpOVWsKLS0tIHhDeUtWMEprRTduYXBXVEtPRHJQ
            ZUZPWlFjOEZtM3NHT3RnNXlzb3JNQWMKP8F1DVpG86sA3pr339uonGqLOMKGwedn
            qTz4MAKuTB3KNU18LoL/JXW8ZNBKNI/+S8F07NKRDZ6wAifsdlIJiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T01:48:19Z"
    mac: ENC[AES256_GCM,data:KUXRTXpjrph57pqnpsY8kjoKn23Vnf3xGQAovAp/IG8PvyC+WnJh+0T4VQpJsfcbI7kqINFg7TRezgOL3SAt0wLHvCYdJurPxDGi4fVOcTaK6733cisUyGus9P9b7hAfnQdlddZJLz1eAstEbb/xFQT4JDf+yglkBB/CFD82dR4=,iv:QDs7GRPj0rA3ZokHKhb29bqdAw9SZiiN/z8x05zf3Cg=,tag:mK0OY2+FdBh3jb1vg+9J0g==,type:str]
    encrypted_regex: key
    version: 3.11.0
