context: talos-k8s-proxmox
contexts:
    talos-k8s-proxmox:
        endpoints:
            - 2a01:4f8:202:3064:1::2d02
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBL3NvOFVoc2FSZHlYNi94M2p0UHN6ekFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXhNakUwTURZeE1ETTNXaGNOTXpVeE1qRXlNRFl4TURNM1dqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUh2YnlJU0syWStOaFQzaE1ZY3FwS3dISk1BWUlvSFpLUzdPClFmOEpSK0c2bzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkUxRkpjOG9pRDlIcGMrUApFeWNjUFpoMmNITkpNQVVHQXl0bGNBTkJBS0tUSXV4cFduVW5DOGg4VmhlK2E1ZWZXb25qTUcxN2V6RDNZZUVmCis5aGw5TXFrMmRHbXpaRWptTmN1UWZrT1VFRVNFcUNMNVpEdUpxc1g3VDU0NUFrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLVENCM0tBREFnRUNBaEVBZzhxRUJ3T1llSExFc0x0UGRPZi8yakFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXhNakUwTURZeE1ETTNXaGNOTWpZeE1qRTBNRFl4TURNM1dqQVRNUkV3RHdZRApWUVFLRXdodmN6cGhaRzFwYmpBcU1BVUdBeXRsY0FNaEFOSlk1a1pWWmNFUFBueGVMdDk2aDBvcFFhcExEMEJPCndTaUJqeHdxVllOc28wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVVUVVVsenlpSVAwZWx6NDhUSnh3OW1IWndjMGt3QlFZREsyVndBMEVBcTU1OApiUUhnV1p3SjhYb1lWd2FZamxLN0hXZHVOSlh0SXdmbURvQWFIQ3BsMURIMU9NWnVPOStxT3ZzQkRHWjZ5V2ozCkdFL0luNm9reVYreG8wemNBdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: ENC[AES256_GCM,data:4Ntj/vTYaQQdQwNpG4cFZYzdqAfoXl3e04Xvwl8UhDHGKzIXVRye09oMmGpYIibqIz1NIj5cLFAanugtsT2v8JCPiDZItrIo4rYG+jyxNV9fKxp/KmOhLoxEUUrVI812vlbOGuiAdU9RDL3WFDmVwurB4Clz1csbEPHEV49ZA5zcvtJMMCXYc6qQG1hbQ73+PB6iAuJHH3D8pj/mRPgDK6i5Hvw9bxpQJmpF4l8wiBv64etY,iv:WDy8EHDx2QicNfHgR2a+ZLyktPFpzeRHn5kKyb1rSNU=,tag:XV7oRgVrUazfeGxrIuF2Ag==,type:str]
sops:
    age:
        - recipient: age1ngvggfld4elq68926uczkes9rcqfjhnqn0tr6l8avyp4h46qzucqvx3sdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZ0VsZ3FzUlF3V0RPMlFi
            Z1RhdHJ1Y2wwb2YvNUtSLzFHRmZseUh5NVhnCjRQMi9pbzAxcjhkNzYrNWFOWEZy
            V0czTTdTbmwzM2FMWitTa3pPWDgxNWMKLS0tIGNVbUh6bXVyNXN4Q1F1RFhPYUho
            OVVUdWtGNEFhM3RkKzl6TVVzekozR0EKzH89q97oxaHVwSW2w9YfzA+TghD83ZVg
            LCysOGxllQZNNzLeNGMMxeIOXOCoxaPjR3ywPDhHUyZ1YeH5BPCODw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T07:08:22Z"
    mac: ENC[AES256_GCM,data:CPLJsnUTTyoFTW+PN9LpQzupz4qZpfQGXmhDQZ+qsj2mKqOzqu/StlFAglePHGB5jQCEgC9CASC1BfsI97F2d0tzeFY4CbGsnkb5kuPx+EYuhgdMVFV57hvM0ULCFKRLPb34orBQgQpqNYR3HW+OBlrO1cDtBjYiB8TA6wbreQU=,iv:sMSFAr2DoxfuoEZqhPoeJYZbmfQ8JeHNwdR5CICkdBo=,tag:Z3UuZH7PUGY6IyGcXKyl0w==,type:str]
    encrypted_regex: key
    version: 3.11.0
